services:
  - type: web
    name: flowgenix-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY_ENCRYPTION_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://flowgenix-frontend.vercel.app,https://*.vercel.app"
      - key: CHROMA_PERSIST_DIRECTORY
        value: "/opt/render/project/chroma_db"
      - key: UPLOAD_DIR
        value: "/opt/render/project/uploads"
      - key: APP_NAME
        value: "Flowgenix"
      - key: APP_VERSION
        value: "1.0.0"
      - key: DEBUG
        value: "False"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    healthCheckPath: /health
