services:
  - type: web
    name: flowgenix-backend
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: API_KEY_ENCRYPTION_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://your-frontend-app.vercel.app"
      - key: CHROMA_PERSIST_DIRECTORY
        value: "/opt/render/project/src/chroma_db"
      - key: UPLOAD_DIR
        value: "/opt/render/project/src/uploaded_docs"
    autoDeploy: true
    buildFilter:
      paths:
        - backend/**
        - render.yaml
    healthCheckPath: /health
    
databases:
  - name: flowgenix-db
    databaseName: flowgenix
    user: flowgenix
    plan: free
    region: oregon
