apiVersion: v1
kind: ConfigMap
metadata:
  name: flowgenix-config
  namespace: flowgenix
data:
  POSTGRES_USER: "flowgenix"
  POSTGRES_DB: "flowgenix"
  CHROMA_SERVER_HOST: "0.0.0.0"
  CHROMA_SERVER_HTTP_PORT: "8000"

---
apiVersion: v1
kind: Secret
metadata:
  name: flowgenix-secrets
  namespace: flowgenix
type: Opaque
stringData:
  POSTGRES_PASSWORD: "flowgenix"
  SECRET_KEY: "supersecret-change-in-production"
  GEMINI_API_KEY: "your-gemini-api-key"
  BRAVE_API_KEY: "your-brave-api-key"
  SERPAPI_KEY: "your-serpapi-key"
